export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

// export const GET_PROFILE = 'GET_PROFILE';
// export const GET_PROFILES = 'GET_PROFILES';
// export const UPDATE_PROFILE = 'UPDATE_PROFILE';
// export const CLEAR_PROFILE = 'CLEAR_PROFILE';
// export const PROFILE_ERROR = 'PROFILE_ERROR';

export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAIL = 'CREATE_FAIL';
export const GET_CREATED_BOOKS_SUCCESS = 'GET_CREATED_BOOKS_SUCCESS';
export const GET_CREATED_BOOKS_FAIL = 'GET_CREATED_BOOKS_FAIL';
