export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS"
export const LOAD_BOOKS_FAIL = "LOAD_BOOKS_FAIL"

export const LOAD_BOOK_SUCCESS = "LOAD_BOOK_SUCCESS"
export const LOAD_BOOK_FAIL = "LOAD_BOOK_FAIL"

export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS";
export const LOAD_GENRES_FAIL = "LOAD_GENRES_FAIL";

export const GET_RANKINGS_SUCCESS = "GET_RANKINGS_SUCCESS";
export const GET_RANKINGS_FAIL = "GET_RANKINGS_FAIL";

export const LOAD_LIBRARY_SUCCESS = "LOAD_LIBRARY_SUCCESS";
export const LOAD_LIBRARY_FAIL = "LOAD_LIBRARY_FAIL";
export const UPDATE_LIBRARY_SUCCESS = "UPDATE_LIBRARY_SUCCESS";
export const UPDATE_LIBRARY_FAIL = "UPDATE_LIBRARY_FAIL";
export const CHECK_LIBRARY_SUCCESS = "CHECK_LIBRARY_SUCCESS";
export const CHECK_LIBRARY_FAIL = "CHECK_LIBRARY_FAIL";
export const ADD_TO_LIBRARY_SUCCESS = "ADD_TO_LIBRARY_SUCCESS";
export const ADD_TO_LIBRARY_FAIL = "ADD_TO_LIBRARY_FAIL";
export const REMOVE_FROM_LIBRARY_SUCCESS = "REMOVE_FROM_LIBRARY_SUCCESS";
export const REMOVE_FROM_LIBRARY_FAIL = "REMOVE_FROM_LIBRARY_FAIL";

export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS";
export const LOAD_REVIEWS_FAIL = "LOAD_REVIEWS_FAIL";
export const POST_REVIEWS_SUCCESS = "POST_REVIEWS_SUCCESS";
export const POST_REVIEWS_FAIL = "POST_REVIEWS_FAIL";