export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

// export const GET_PROFILE = 'GET_PROFILE';
// export const GET_PROFILES = 'GET_PROFILES';
// export const UPDATE_PROFILE = 'UPDATE_PROFILE';
// export const CLEAR_PROFILE = 'CLEAR_PROFILE';
// export const PROFILE_ERROR = 'PROFILE_ERROR';

export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAIL = 'CREATE_FAIL';
export const GET_CREATED_BOOKS_SUCCESS = 'GET_CREATED_BOOKS_SUCCESS';
export const GET_CREATED_BOOKS_FAIL = 'GET_CREATED_BOOKS_FAIL';

export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAIL = "GET_BOOKS_FAIL";

export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_FAIL = "GET_GENRES_FAIL";

export const GET_RANKINGS_SUCCESS = "GET_RANKINGS_SUCCESS";
export const GET_RANKINGS_FAIL = "GET_RANKINGS_FAIL";

export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS"; 
export const GET_BOOK_FAIL = "GET_BOOK_FAIL";
export const GET_CHAPTER_SUCCESS = "GET_CHAPTER_SUCCESS";
export const GET_CHAPTER_FAIL = "GET_CHAPTER_FAIL";

export const GET_LIBRARY_SUCCESS = "GET_LIBRARY_SUCCESS";
export const GET_LIBRARY_FAIL = "GET_LIBRARY_FAIL";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";
export const REMOVE_FROM_LIBRARY_SUCCESS = "REMOVE_FROM_LIBRARY_SUCCESS";
export const REMOVE_FROM_LIBRARY_FAIL = "REMOVE_FROM_LIBRARY_FAIL";

export const CREATE_CHAPTER_SUCCESS = 'CREATE_CHAPTER_SUCCESS';
export const CREATE_CHAPTER_FAIL = 'CREATE_CHAPTER_FAIL';
export const UPDATE_CHAPTER_SUCCESS = 'UPDATE_CHAPTER_SUCCESS';
export const UPDATE_CHAPTER_FAIL = 'UPDATE_CHAPTER_FAIL';

export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";
export const DELETE_CHAPTER_SUCCESS = "DELETE_CHAPTER_SUCCESS";
export const DELETE_CHAPTER_FAIL = "DELETE_CHAPTER_FAIL";